// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"database/sql"
	"go_playground/Go-000/Week04/myApp/internal/app/myApp/biz"
	"go_playground/Go-000/Week04/myApp/internal/app/myApp/service"
)

// Injectors from wire.go:

func initializeMyApp(db *sql.DB) service.Service {
	bizBiz := biz.NewBiz(db)
	serviceService := service.NewService(bizBiz)
	return serviceService
}
